[pytest]
asyncio_mode = auto
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:pytesseract
    ignore::DeprecationWarning:pkg_resources
markers =
    anyio: marks tests as async (anyio)
