services:
  - type: web
    name: game-analysis-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Host=aws-1-ap-northeast-1.pooler.supabase.com; Port=6543; Database=postgres; Username=postgres.nhmizaojhikpgbvxdpcw; Password=Hxvf1234@12@; SSL Mode=Require; Trust Server Certificate=true; Pooling=false"
      - key: Jwt__Key
        value: "ThisIsAVerySecretKeyForJWTDemo1234567890"
      - key: Jwt__Issuer
        value: "GameAIAnalysis"
      - key: Jwt__Audience
        value: "GameAIAnalysisUsers"
      - key: Jwt__DurationInMinutes
        value: "60"
      - key: Cloudinary__CloudName
        value: "drxbaxbkt"
      - key: Cloudinary__ApiKey
        value: "112143581823739"
      - key: Cloudinary__ApiSecret
        value: "TRaQ0HuVNQnI_85yn2jofvKzQGY"
      - key: OcrApi__BaseUrl
        value: "https://hxvf123-demoocrserver.hf.space"
      - key: OcrApi__ExtractEndpoint
        value: "/api/v1/extract"
      - key: OcrApi__Language
        value: "eng"
      - key: ASPNETCORE_ENVIRONMENT
        value: "Production"
